### ISSUE TITLE
Alternatives to `movedir.js`/`mv`

### ISSUE THREAD

**Issue by cursedstuff** [GmBodhi/create-three-app#12]
[movedir.js](https://github.com/GmBodhi/create-three-app/blob/master/src/scripts/movedir.js) is puzzling...

Why are you deleting and re-creating the entire directory...?
Renaming the root directory is the same, and `mv` can do this. Detect which OS the user is running and use the correct command with `exec` or even `execSync`.

**Comment by cursedstuff** [comment]
`mv` can do this as well?

**Comment by cursedstuff** [comment]
I'm not sure what the problem is...

**Comment by cursedstuff** [comment]
When renaming a folder you can move it inside a folder:
```bash
$ mv /tmp/cta/resources/ target/subdirectory
```

**Comment by CodyJasonBennett** [comment]
`mv` would be prone to corruption if halted at any point; it is not a drop-in replacement.

**Comment by cursedstuff** [comment]
Ok, fair enough. Closing...

**Comment by cursedstuff** [comment]
Actually, what about `cp`? Does it have the same problem?

**Comment by CodyJasonBennett** [comment]
`cp` would be the more direct comparison, but you'd still need to jump through hoops for compatibility and perf regressions that the node team has already made with their `fs` module.

**Comment by cursedstuff** [comment]
Ok makes sense. Thanks.
